scss_files: 'app/assets/scss/*.scss'

linters:
  SelectorDepth:
    enabled: false

  NestingDepth:
    enabled: false

  TrailingWhitespace:
    enabled: false

  ImportantRule:
    enabled: false

  SingleLinePerSelector:
    enabled: false

  ColorVariable:
    enabled: false
